# Generated by Django 4.2.2 on 2023-08-05 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, help_text='for not logged in users', max_length=33, null=True)),
                ('action', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike'), ('watch', 'Watch'), ('report', 'Report'), ('rate', 'Rate')], default='watch', max_length=20)),
                ('extra_info', models.TextField(blank=True, null=True)),
                ('action_date', models.DateTimeField(auto_now_add=True)),
                ('remote_ip', models.CharField(blank=True, max_length=40, null=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediaactions', to='files.media')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='useractions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'action', '-action_date'], name='actions_med_user_id_940054_idx'), models.Index(fields=['session_key', 'action'], name='actions_med_session_fac55a_idx')],
            },
        ),
    ]
